### PR TITLE
Fix multiple things

### LINKED ISSUE #368: selectedOrderRegion is not reset when resolving the 2nd Raid order
When it comes to the second raid the previously raided region is still selected and the user needs to click Reset first:

image

### PR DESCRIPTION
**Pull request by gereon77**
Closes #368

### CODE REVIEW

**Comment by Longwelwind** [comment]
Rebase off `v1.2-branch` and I'll merge

File: agot-bg-game-server/src/client/GameLogListComponent.tsx [hunk 1]
```diff
@@ -83,7 +83,7 @@ export default class GameLogListComponent extends Component<GameLogListComponent
                 return (
                     <>
                         <b>{attacker.name}</b> attacked <b>{attacked ? attacked.name : "a neutral force"}</b> from <b>{attackingRegion.name}</b> to <b>
-                        {attackedRegion.name}</b> with {joinReactNodes(army.map(ut => ut.name), ', ')}.
+                        {attackedRegion.name}</b> with <strong>{joinReactNodes(army.map(ut => ut.name), ', ')}</strong>.
```
Comment (Longwelwind) [inline agot-bg-game-server/src/client/GameLogListComponent.tsx]: Put the `<strong>` inside the `joinReactNodes` so that the commas are not bolded.

File: agot-bg-game-server/src/common/ingame-game-state/westeros-game-state/dark-wings-dark-words-game-state/DarkWingsDarkWordsGameState.ts [hunk 2]
```diff
@@ -23,8 +23,8 @@ export default class DarkWingsDarkWordsGameState extends GameState<WesterosGameS
         this.setChildGameState(new SimpleChoiceGameState(this)).firstStart(this.game.ravenHolder,
             "The holder of the Raven Token can choose between CoK, GoT or None.",
             [
-                "Clash of Kings (Players bid for each power track)",
-                "Game of Thrones (Players gain one power token for each controlled crown icons and ports)",
+                "Clash of Kings (Players bid for each Influence track)",
+                "Game of Thrones (Players gain Power Tokens for controlled Crown icons and ports with ships)",
```
Comment (Longwelwind) [inline agot-bg-game-server/src/common/ingame-game-state/westeros-game-state/dark-wings-dark-words-game-state/DarkWingsDarkWordsGameState.ts]: "Power Tokens" => "Power tokens"

Comment (gereon77) [reply agot-bg-game-server/src/common/ingame-game-state/westeros-game-state/dark-wings-dark-words-game-state/DarkWingsDarkWordsGameState.ts]: Indeed. Rulebook only references "Power Tokens" in headers...
