### PR TITLE
Fix routed units cannot march

### LINKED ISSUE #334: Routed unit should not be able to move during the resolution of a March order

### PR DESCRIPTION
**Pull request by gereon77**
Closes #334

### CODE REVIEW

File: agot-bg-game-server/src/common/cancelled-game-state/CancelledGameState.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ export default class CancelledGameState extends GameState<EntireGame> {
     }
 
     onClientMessage(_user: User, _message: ClientMessage): void {
-        
+        return;
```
Comment (Longwelwind) [inline agot-bg-game-server/src/common/cancelled-game-state/CancelledGameState.ts]: I'll turn off the linter message for empty function, since it's a pattern that we use frequently in the codebase, so no need to add `return;` here.

**Comment by Longwelwind** [comment]
LGTM.

Remove the return and I'll merge!

File: agot-bg-game-server/src/common/cancelled-game-state/CancelledGameState.ts (hunk 1 above)
Comment (gereon77) [reply agot-bg-game-server/src/common/cancelled-game-state/CancelledGameState.ts]: I found that line as a trailing whitespace crept in again. I always try to do a \s$ search before PRing... But sure. I removed the commit.

**Comment by gereon77** [comment]
> 
> 
> LGTM.
> 
> Remove the return and I'll merge!

I have tested it locally with Bara and Stark in round 1. Worked as expected.

**Comment by Longwelwind** [comment]
Sorry, rebase again and I'll merge.

**Comment by gereon77** [comment]
> Sorry, rebase again and I'll merge.

NP :)
